services:
  # --- BASE DE DATOS PROPIA ---
  db:
    image: postgres:15-alpine
    container_name: pastibot_db
    restart: always
    environment:
      POSTGRES_USER: pastibot_user
      POSTGRES_PASSWORD: pastibot_password
      POSTGRES_DB: pastibot_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Puerto 5433 en tu PC mapeado al 5432 del contenedor

  # --- TU BACKEND (API) ---
  api:
    build: .
    container_name: pastibot_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # Sobrescribimos la conexi√≥n para que use la DB interna de Docker
      DATABASE_URL: postgresql://pastibot_user:pastibot_password@db:5432/pastibot_database?schema=public
      NODE_ENV: production
    depends_on:
      - db

volumes:
  postgres_data:
